import { Employee, Lead, FollowUp, Prospect, Proposal, Conversion, Campaign, FieldVisit, SalesTarget, NotificationItem, LeadActivityLog } from '@/types';

export const INITIAL_SALES_TARGET: SalesTarget = {
  id: 'st-01',
  period_month: 'September 2026',
  target_revenue: 1000000, // ₹10L
  target_leads: 900,
  target_prospects: 150,
  target_conversions: 20,
  achieved_revenue: 780000, // ₹7.8L
  achieved_leads: 865,
  achieved_prospects: 142,
  achieved_conversions: 17,
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-01',
    profile_id: 'prof-01',
    employee_code: 'HM-101',
    full_name: 'Abinaya',
    email: 'abinaya@hatsoffmedia.com',
    phone: '+91 98765 43210',
    designation: 'Senior Sales Executive',
    team_name: 'Outbound & Corporate',
    leads_assigned: 82,
    new_leads_created: 35,
    calls_count: 68,
    activities_count: 115,
    followups_completed: 42,
    overdue_followups: 2,
    prospects_count: 18,
    proposals_count: 8,
    won_count: 4,
    lost_count: 2,
    conversion_rate: 4.88,
    revenue: 180000, // ₹1.8L
    target: 220000,
    achievement_pct: 81.8,
    status: 'Active',
  },
  {
    id: 'emp-02',
    profile_id: 'prof-02',
    employee_code: 'HM-102',
    full_name: 'Kumar',
    email: 'kumar@hatsoffmedia.com',
    phone: '+91 98765 43211',
    designation: 'Sales Executive',
    team_name: 'Field Sales',
    leads_assigned: 71,
    new_leads_created: 28,
    calls_count: 52,
    activities_count: 96,
    followups_completed: 35,
    overdue_followups: 1,
    prospects_count: 15,
    proposals_count: 6,
    won_count: 3,
    lost_count: 3,
    conversion_rate: 4.22,
    revenue: 140000, // ₹1.4L
    target: 180000,
    achievement_pct: 77.7,
    status: 'Active',
  },
  {
    id: 'emp-03',
    profile_id: 'prof-03',
    employee_code: 'HM-103',
    full_name: 'Sneha',
    email: 'sneha@hatsoffmedia.com',
    phone: '+91 98765 43212',
    designation: 'Digital Growth Specialist',
    team_name: 'Digital Campaigns',
    leads_assigned: 65,
    new_leads_created: 30,
    calls_count: 48,
    activities_count: 88,
    followups_completed: 31,
    overdue_followups: 1,
    prospects_count: 14,
    proposals_count: 7,
    won_count: 3,
    lost_count: 1,
    conversion_rate: 4.61,
    revenue: 150000, // ₹1.5L
    target: 200000,
    achievement_pct: 75.0,
    status: 'Active',
  },
  {
    id: 'emp-04',
    profile_id: 'prof-04',
    employee_code: 'HM-104',
    full_name: 'Rahul',
    email: 'rahul@hatsoffmedia.com',
    phone: '+91 98765 43213',
    designation: 'Field Account Manager',
    team_name: 'Field Sales',
    leads_assigned: 58,
    new_leads_created: 22,
    calls_count: 45,
    activities_count: 79,
    followups_completed: 28,
    overdue_followups: 2,
    prospects_count: 11,
    proposals_count: 5,
    won_count: 2,
    lost_count: 2,
    conversion_rate: 3.44,
    revenue: 110000, // ₹1.1L
    target: 150000,
    achievement_pct: 73.3,
    status: 'Active',
  },
  {
    id: 'emp-05',
    profile_id: 'prof-05',
    employee_code: 'HM-105',
    full_name: 'Priya',
    email: 'priya@hatsoffmedia.com',
    phone: '+91 98765 43214',
    designation: 'Outbound Specialist',
    team_name: 'Outbound & Corporate',
    leads_assigned: 52,
    new_leads_created: 24,
    calls_count: 40,
    activities_count: 70,
    followups_completed: 25,
    overdue_followups: 1,
    prospects_count: 10,
    proposals_count: 4,
    won_count: 2,
    lost_count: 1,
    conversion_rate: 3.84,
    revenue: 100000, // ₹1.0L
    target: 150000,
    achievement_pct: 66.6,
    status: 'Active',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    lead_code: 'LEAD-865',
    created_at: '2026-09-22T09:30:00Z',
    company_name: 'Apex Global Solutions',
    contact_person: 'Rajesh Sharma',
    phone: '+91 98112 34567',
    whatsapp: '+91 98112 34567',
    email: 'rajesh@apexglobal.com',
    website: 'https://apexglobal.com',
    location: 'Mumbai, Maharashtra',
    source: 'Website',
    service: 'Social Media Management & Performance Ads',
    estimated_budget: 150000,
    assigned_employee_id: 'emp-01',
    assigned_employee_name: 'Abinaya',
    status: 'Interested',
    priority: 'High',
    next_followup_date: '2026-09-22',
    next_followup_time: '14:30',
    last_contacted_at: '2026-09-21T16:00:00Z',
    notes: 'Client looking for full digital rebranding & lead generation campaign for Q4.',
    created_by: 'Abinaya',
  },
  {
    id: 'lead-102',
    lead_code: 'LEAD-864',
    created_at: '2026-09-21T11:00:00Z',
    company_name: 'Zenith Retail Chain',
    contact_person: 'Pooja Verma',
    phone: '+91 98223 45678',
    whatsapp: '+91 98223 45678',
    email: 'pooja@zenithretail.in',
    website: 'https://zenithretail.in',
    location: 'Pune, Maharashtra',
    source: 'Field Visit',
    service: 'SEO & Content Marketing',
    estimated_budget: 80000,
    assigned_employee_id: 'emp-02',
    assigned_employee_name: 'Kumar',
    status: 'Follow-up',
    priority: 'High',
    next_followup_date: '2026-09-21',
    next_followup_time: '11:00',
    last_contacted_at: '2026-09-20T10:30:00Z',
    notes: 'Field visit completed. Demo scheduled with marketing director.',
    created_by: 'Kumar',
  },
  {
    id: 'lead-103',
    lead_code: 'LEAD-863',
    created_at: '2026-09-21T14:15:00Z',
    company_name: 'Nova Tech Labs',
    contact_person: 'Vikram Mehta',
    phone: '+91 98334 56789',
    whatsapp: '+91 98334 56789',
    email: 'vikram@novatech.co',
    website: 'https://novatech.co',
    location: 'Bengaluru, Karnataka',
    source: 'Cold Call',
    service: 'PPC & Google Ads',
    estimated_budget: 120000,
    assigned_employee_id: 'emp-01',
    assigned_employee_name: 'Abinaya',
    status: 'Proposal Sent',
    priority: 'High',
    next_followup_date: '2026-09-22',
    next_followup_time: '16:00',
    last_contacted_at: '2026-09-21T17:00:00Z',
    notes: 'Proposal sent for ₹1.2L monthly retainer. Awaiting signoff.',
    created_by: 'Abinaya',
  },
  {
    id: 'lead-104',
    lead_code: 'LEAD-862',
    created_at: '2026-09-20T10:00:00Z',
    company_name: 'BrightSpark Education',
    contact_person: 'Ananya Roy',
    phone: '+91 98445 67890',
    whatsapp: '+91 98445 67890',
    email: 'ananya@brightspark.edu.in',
    website: 'https://brightspark.edu.in',
    location: 'Delhi NCR',
    source: 'Digital Marketing',
    service: 'Influencer & Brand Marketing',
    estimated_budget: 250000,
    assigned_employee_id: 'emp-03',
    assigned_employee_name: 'Sneha',
    status: 'Won',
    priority: 'High',
    next_followup_date: '2026-09-25',
    next_followup_time: '10:00',
    last_contacted_at: '2026-09-20T15:00:00Z',
    notes: 'Deal closed for ₹2.5L. Onboarding meeting scheduled.',
    created_by: 'Sneha',
  },
  {
    id: 'lead-105',
    lead_code: 'LEAD-861',
    created_at: '2026-09-19T16:30:00Z',
    company_name: 'Horizon Healthcare',
    contact_person: 'Dr. Suresh Rao',
    phone: '+91 98556 78901',
    whatsapp: '+91 98556 78901',
    email: 'suresh@horizonhealth.org',
    location: 'Hyderabad, Telangana',
    source: 'Cold DM',
    service: 'Social Media Management',
    estimated_budget: 60000,
    assigned_employee_id: 'emp-04',
    assigned_employee_name: 'Rahul',
    status: 'Contacted',
    priority: 'Medium',
    next_followup_date: '2026-09-23',
    next_followup_time: '11:30',
    last_contacted_at: '2026-09-19T17:00:00Z',
    notes: 'Responded to LinkedIn DM. Requesting introductory brochure.',
    created_by: 'Rahul',
  },
  {
    id: 'lead-106',
    lead_code: 'LEAD-860',
    created_at: '2026-09-18T09:00:00Z',
    company_name: 'Urban Living Real Estate',
    contact_person: 'Manish Gupta',
    phone: '+91 98667 89012',
    whatsapp: '+91 98667 89012',
    email: 'mgupta@urbanliving.in',
    website: 'https://urbanliving.in',
    location: 'Thane, Maharashtra',
    source: 'Website',
    service: 'Lead Gen Ads & Landing Page Design',
    estimated_budget: 300000,
    assigned_employee_id: 'emp-05',
    assigned_employee_name: 'Priya',
    status: 'Prospect',
    priority: 'High',
    next_followup_date: '2026-09-22',
    next_followup_time: '12:00',
    last_contacted_at: '2026-09-21T12:00:00Z',
    notes: 'High potential luxury residential leads campaign.',
    created_by: 'Priya',
  },
];

export const INITIAL_FOLLOWUPS: FollowUp[] = [
  // OVERDUE FOLLOW-UPS (7 items)
  {
    id: 'fu-01',
    lead_id: 'lead-102',
    company_name: 'Zenith Retail Chain',
    contact_person: 'Pooja Verma',
    phone: '+91 98223 45678',
    assigned_employee_id: 'emp-02',
    assigned_employee_name: 'Kumar',
    type: 'Field Visit',
    followup_date: '2026-09-20',
    followup_time: '11:00',
    priority: 'High',
    purpose: 'In-person meeting with Marketing Head for SEO scope',
    status: 'Overdue',
    last_activity: '19 Sep Field Visit completed',
  },
  {
    id: 'fu-02',
    lead_id: 'lead-107',
    company_name: 'Vanguard Logistics',
    contact_person: 'Sanjay Dutt',
    phone: '+91 98778 90123',
    assigned_employee_id: 'emp-01',
    assigned_employee_name: 'Abinaya',
    type: 'Call',
    followup_date: '2026-09-21',
    followup_time: '15:00',
    priority: 'High',
    purpose: 'Discuss proposal changes for performance marketing',
    status: 'Overdue',
    last_activity: '20 Sep Call completed Spoke for 6 minutes',
  },
  {
    id: 'fu-03',
    lead_id: 'lead-108',
    company_name: 'Solace Spa & Wellness',
    contact_person: 'Meera Iyer',
    phone: '+91 98889 01234',
    assigned_employee_id: 'emp-03',
    assigned_employee_name: 'Sneha',
    type: 'WhatsApp',
    followup_date: '2026-09-21',
    followup_time: '16:30',
    priority: 'Medium',
    purpose: 'Share package pricing via WhatsApp catalog',
    status: 'Overdue',
    last_activity: '20 Sep WhatsApp message sent',
  },
  {
    id: 'fu-04',
    lead_id: 'lead-109',
    company_name: 'NextGen Financial',
    contact_person: 'Karthik Raja',
    phone: '+91 98990 12345',
    assigned_employee_id: 'emp-04',
    assigned_employee_name: 'Rahul',
    type: 'Meeting',
    followup_date: '2026-09-20',
    followup_time: '14:00',
    priority: 'High',
    purpose: 'Virtual demo of campaign dashboard',
    status: 'Overdue',
    last_activity: '18 Sep Lead assigned to Rahul',
  },
  {
    id: 'fu-05',
    lead_id: 'lead-110',
    company_name: 'Gourmet Bites India',
    contact_person: 'Chef Alok',
    phone: '+91 98001 23456',
    assigned_employee_id: 'emp-05',
    assigned_employee_name: 'Priya',
    type: 'Call',
    followup_date: '2026-09-21',
    followup_time: '10:00',
    priority: 'Medium',
    purpose: 'Followup on menu photography requirement',
    status: 'Overdue',
    last_activity: '19 Sep Call completed',
  },
  {
    id: 'fu-06',
    lead_id: 'lead-111',
    company_name: 'Titanium Motors',
    contact_person: 'Sunil Shetty',
    phone: '+91 98112 99887',
    assigned_employee_id: 'emp-01',
    assigned_employee_name: 'Abinaya',
    type: 'Email',
    followup_date: '2026-09-20',
    followup_time: '17:00',
    priority: 'Low',
    purpose: 'Send case studies for auto dealership campaigns',
    status: 'Overdue',
    last_activity: '18 Sep Email sent',
  },
  {
    id: 'fu-07',
    lead_id: 'lead-112',
    company_name: 'EcoClean Services',
    contact_person: 'Nitin Patel',
    phone: '+91 98223 88776',
    assigned_employee_id: 'emp-02',
    assigned_employee_name: 'Kumar',
    type: 'Call',
    followup_date: '2026-09-21',
    followup_time: '12:30',
    priority: 'Medium',
    purpose: 'Finalize local SEO audit review',
    status: 'Overdue',
    last_activity: '19 Sep Call completed',
  },

  // TODAY FOLLOW-UPS (21 items sample top items)
  {
    id: 'fu-10',
    lead_id: 'lead-101',
    company_name: 'Apex Global Solutions',
    contact_person: 'Rajesh Sharma',
    phone: '+91 98112 34567',
    assigned_employee_id: 'emp-01',
    assigned_employee_name: 'Abinaya',
    type: 'Call',
    followup_date: '2026-09-22',
    followup_time: '14:30',
    priority: 'High',
    purpose: 'Finalize budget approval & service scope',
    status: 'Today',
    last_activity: '21 Sep Spoke for 8 minutes',
  },
  {
    id: 'fu-11',
    lead_id: 'lead-103',
    company_name: 'Nova Tech Labs',
    contact_person: 'Vikram Mehta',
    phone: '+91 98334 56789',
    assigned_employee_id: 'emp-01',
    assigned_employee_name: 'Abinaya',
    type: 'Call',
    followup_date: '2026-09-22',
    followup_time: '16:00',
    priority: 'High',
    purpose: 'Review proposal feedback & closure terms',
    status: 'Today',
    last_activity: '21 Sep Proposal sent',
  },
  {
    id: 'fu-12',
    lead_id: 'lead-106',
    company_name: 'Urban Living Real Estate',
    contact_person: 'Manish Gupta',
    phone: '+91 98667 89012',
    assigned_employee_id: 'emp-05',
    assigned_employee_name: 'Priya',
    type: 'Meeting',
    followup_date: '2026-09-22',
    followup_time: '12:00',
    priority: 'High',
    purpose: 'Present ad creative strategy & target audience segments',
    status: 'Today',
    last_activity: '21 Sep Meeting scheduled',
  },

  // UPCOMING FOLLOW-UPS (34 items sample)
  {
    id: 'fu-30',
    lead_id: 'lead-104',
    company_name: 'BrightSpark Education',
    contact_person: 'Ananya Roy',
    phone: '+91 98445 67890',
    assigned_employee_id: 'emp-03',
    assigned_employee_name: 'Sneha',
    type: 'Meeting',
    followup_date: '2026-09-25',
    followup_time: '10:00',
    priority: 'High',
    purpose: 'Onboarding & kick-off call for influencer campaign',
    status: 'Upcoming',
    last_activity: '20 Sep Lead converted to Won',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-01',
    proposal_code: 'PROP-2026-051',
    lead_id: 'lead-103',
    company_name: 'Nova Tech Labs',
    contact_person: 'Vikram Mehta',
    proposal_date: '2026-09-21',
    proposal_value: 120000,
    service: 'PPC & Google Ads',
    status: 'Sent',
    sent_by_id: 'emp-01',
    sent_by_name: 'Abinaya',
    expected_decision_date: '2026-09-24',
    notes: 'Includes keyword research, monthly 10% performance incentive clause.',
  },
  {
    id: 'prop-02',
    proposal_code: 'PROP-2026-050',
    lead_id: 'lead-104',
    company_name: 'BrightSpark Education',
    contact_person: 'Ananya Roy',
    proposal_date: '2026-09-18',
    proposal_value: 250000,
    service: 'Influencer & Brand Marketing',
    status: 'Accepted',
    sent_by_id: 'emp-03',
    sent_by_name: 'Sneha',
    expected_decision_date: '2026-09-20',
    notes: 'Approved by Managing Director. Contract signed.',
  },
  {
    id: 'prop-03',
    proposal_code: 'PROP-2026-049',
    lead_id: 'lead-106',
    company_name: 'Urban Living Real Estate',
    contact_person: 'Manish Gupta',
    proposal_date: '2026-09-20',
    proposal_value: 300000,
    service: 'Lead Gen Ads & Landing Page Design',
    status: 'Negotiation',
    sent_by_id: 'emp-05',
    sent_by_name: 'Priya',
    expected_decision_date: '2026-09-26',
    notes: 'Negotiating payment terms (50% advance / 50% milestone).',
  },
];

export const INITIAL_CONVERSIONS: Conversion[] = [
  {
    id: 'conv-01',
    conversion_code: 'WON-2026-017',
    lead_id: 'lead-104',
    company_name: 'BrightSpark Education',
    sales_executive_id: 'emp-03',
    sales_executive_name: 'Sneha',
    service: 'Influencer & Brand Marketing',
    original_lead_source: 'Digital Marketing',
    campaign_name: 'Q3 EdTech Growth Drive',
    proposal_value: 250000,
    final_deal_value: 250000,
    converted_date: '2026-09-20',
    payment_status: 'Paid Full',
    notes: 'Annual brand marketing contract.',
  },
  {
    id: 'conv-02',
    conversion_code: 'WON-2026-016',
    lead_id: 'lead-115',
    company_name: 'Starlight Jewels',
    sales_executive_id: 'emp-01',
    sales_executive_name: 'Abinaya',
    service: 'Social Media Management',
    original_lead_source: 'Website',
    campaign_name: 'Festive Jewelry Promo',
    proposal_value: 180000,
    final_deal_value: 180000,
    converted_date: '2026-09-18',
    payment_status: 'Partially Paid',
    notes: '6 month social retainer.',
  },
  {
    id: 'conv-03',
    conversion_code: 'WON-2026-015',
    lead_id: 'lead-116',
    company_name: 'Matrix Cloud Software',
    sales_executive_id: 'emp-02',
    sales_executive_name: 'Kumar',
    service: 'SEO & Content Marketing',
    original_lead_source: 'Field Visit',
    campaign_name: 'SaaS B2B Outreach',
    proposal_value: 140000,
    final_deal_value: 140000,
    converted_date: '2026-09-15',
    payment_status: 'Paid Full',
    notes: 'Organic SEO audit and link building.',
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-01',
    name: 'Q3 EdTech Growth Drive',
    type: 'Digital Marketing',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
    owner_name: 'Sneha',
    budget: 150000,
    target_leads: 180,
    actual_leads: 150,
    prospects_count: 24,
    conversions_count: 5,
    revenue_generated: 320000,
    status: 'Active',
  },
  {
    id: 'camp-02',
    name: 'SaaS B2B Field Visits',
    type: 'Field Campaign',
    start_date: '2026-09-05',
    end_date: '2026-09-28',
    owner_name: 'Kumar',
    budget: 60000,
    target_leads: 50,
    actual_leads: 45,
    prospects_count: 12,
    conversions_count: 5,
    revenue_generated: 240000,
    status: 'Active',
  },
  {
    id: 'camp-03',
    name: 'Cold Outreach Blitz',
    type: 'Outbound Calling',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
    owner_name: 'Abinaya',
    budget: 40000,
    target_leads: 150,
    actual_leads: 120,
    prospects_count: 18,
    conversions_count: 4,
    revenue_generated: 180000,
    status: 'Active',
  },
];

export const INITIAL_FIELD_VISITS: FieldVisit[] = [
  {
    id: 'fv-01',
    employee_id: 'emp-02',
    employee_name: 'Kumar',
    date: '2026-09-22',
    company_name: 'Zenith Retail Chain',
    contact_person: 'Pooja Verma',
    location: 'FC Road, Pune',
    visit_purpose: 'In-person presentation to Board of Directors',
    meeting_status: 'Scheduled',
    discussion: 'Discussing omnichannel marketing strategy & retail store footfall ads.',
    potential_value: 120000,
    notes: 'Bring sample campaign pitch deck.',
  },
  {
    id: 'fv-02',
    employee_id: 'emp-04',
    employee_name: 'Rahul',
    date: '2026-09-22',
    company_name: 'Metro Hospitals',
    contact_person: 'Dr. Nair',
    location: 'Bandra West, Mumbai',
    visit_purpose: 'Requirement Discussion',
    meeting_status: 'Completed',
    discussion: 'Client requested lead generation for orthopedic surgery wing.',
    requirement: 'Google Ads & Meta Lead Form Ads.',
    outcome: 'Proposal requested by Friday.',
    potential_value: 200000,
  },
];

export const INITIAL_ACTIVITIES: LeadActivityLog[] = [
  {
    id: 'act-01',
    lead_id: 'lead-101',
    company_name: 'Apex Global Solutions',
    author_name: 'Abinaya',
    timestamp: '2026-09-22 10:32 AM',
    type: 'Call',
    description: 'Call completed Spoke for 8 minutes. Discussed monthly retainer terms.',
  },
  {
    id: 'act-02',
    lead_id: 'lead-101',
    company_name: 'Apex Global Solutions',
    author_name: 'Abinaya',
    timestamp: '2026-09-21 04:15 PM',
    type: 'WhatsApp',
    description: 'WhatsApp message sent with Hatsoff Media corporate portfolio PDF.',
  },
  {
    id: 'act-03',
    lead_id: 'lead-102',
    company_name: 'Zenith Retail Chain',
    author_name: 'Kumar',
    timestamp: '2026-09-20 11:00 AM',
    type: 'Follow-up',
    description: 'Follow-up rescheduled to 21 Sep for decision maker availability.',
  },
  {
    id: 'act-04',
    lead_id: 'lead-103',
    company_name: 'Nova Tech Labs',
    author_name: 'Abinaya',
    timestamp: '2026-09-21 05:00 PM',
    type: 'Proposal',
    description: 'Lead status changed: Contacted → Proposal Sent.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: '7 Overdue Follow-ups Require Action',
    message: 'Attention: You have overdue follow-ups pending for Zenith Retail Chain, Vanguard Logistics, and 5 others.',
    timestamp: '10 mins ago',
    type: 'followup_overdue',
    is_read: false,
    link: '/activities/follow-ups',
  },
  {
    id: 'notif-02',
    title: 'New High Priority Lead Assigned',
    message: 'Apex Global Solutions (Estimated Budget: ₹1.5L) assigned to Abinaya.',
    timestamp: '1 hour ago',
    type: 'lead_assigned',
    is_read: false,
    link: '/leads/lead-101',
  },
  {
    id: 'notif-03',
    title: 'Monthly Target Milestone Achieved!',
    message: 'Hatsoff Sales Control Center reached 78% of monthly target (₹7.8L of ₹10L).',
    timestamp: '3 hours ago',
    type: 'target_milestone',
    is_read: true,
    link: '/team/targets',
  },
];
